// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

package ncaction

import "github.com/raohwork/task/noctx/nctask"

// Action is a specialized [nctask.Task] which accepts one param.
//
// It is designed to interact with the value generated by [Data] to do something.
// An [nctask.Task] is created after you bind action and data together. It is
// suggested to name it using short phrase to describe what will it do, like
// "saveToDB", to write code like this:
//
//	Use(resp).To(saveToDB)
//	Do(saveToDB).Use(resp)
//
// Both means if value is generated by resp successfully, save it to DB and return
// any error.
type Action[T any] func(T) error

// Do wraps f into Action, mostly for for typing purpose.
func Do[T any](f func(T) error) Action[T] { return f }

// NoErrDo creates Action from non-cancellable, never-fail function.
func NoErrDo[T any](f func(T)) Action[T] {
	return func(v T) error { f(v); return nil }
}

// Then creates an Action which runs next after act is finished successfully.
func (act Action[T]) Then(next Action[T]) Action[T] {
	return func(v T) error {
		if err := act(v); err != nil {
			return err
		}
		return next(v)
	}
}

// NoErr converts Action into simple function that ignores error.
func (a Action[T]) NoErr() func(T) { return func(v T) { a(v) } }

// Use creates a [nctask.Task] that executes the action with Data. The value of data
// is generated on-the-fly.
func (a Action[T]) Use(d Data[T]) nctask.Task {
	return func() error {
		v, err := d()
		if err != nil {
			return err
		}
		return a(v)
	}
}

// Apply creates a [nctask.Task] that executes the action with a value.
func (a Action[T]) Apply(v T) nctask.Task {
	return func() error { return a(v) }
}

// Pre wraps a to run f before it.
func (a Action[T]) Pre(f func(v T)) Action[T] {
	return func(v T) error {
		f(v)
		return a(v)
	}
}

// Post wraps a to run f after it.
func (a Action[T]) Post(f func(T, error)) Action[T] {
	return func(v T) error {
		err := a(v)
		f(v, err)
		return err
	}
}

// AlterError wraps a to convert error before return it.
func (a Action[T]) AlterError(f func(error) error) Action[T] {
	return func(v T) error {
		err := a(v)
		return f(err)
	}
}

// Defer wraps a to run f after it.
func (a Action[T]) Defer(f func()) Action[T] {
	return func(v T) error {
		err := a(v)
		f()
		return err
	}
}

// Task is a predefined Action used to convert Data into [nctask.Task] like
//
//	err := Get(saveToDB).By(dbConn).From(myData).To(Task).Run(ctx)
func Task[T any](_ T) error { return nil }
